#print("Strings Introduction:")
#print("string indexing:")
s="Codegnan"
#print(s[4])
#print(s[-2])
#print(" string slicing:")
#print(s[:])
#print(s[:5])
#print(s[-1:-5:-1])
#print(s[-3])
#print(s[::-1])
#print(s[-1:-9:-1])
#print(s[-3::-1])
#print(s[4::-1])
#print(s[2:10:1])
print("string concatenation")
s1="code"
s2="gnan"
#print(s1+s2)
#print(s1+s1)
#print(s1*10)
#print(s2+s2+s2)
#print(s[4]+s[4])
print(s[4]+'z'+s[-4])
